# Generated by Django 4.1.1 on 2022-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findtalent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='github_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
