# Generated by Django 4.1.1 on 2022-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findtalent', '0003_remove_individual_compatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='bio',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='location',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='skills',
            field=models.CharField(max_length=10000),
        ),
    ]
